# Replace the text below to customize your site
site_name: Hannah Peevey - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Student Name
copyright: Copyleft 2023 "Student Name" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://fablabbcn.github.io/mdef-template/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - Home: home/index.md
  - About:
      - About Me: about/index.md
  - Master Project:
      - Overview: project/index.md
      - Term 1: term1/index.md
      - Design Studio 1: term1/design-studio-1.md
      - Living With Your Own Ideas: term1/living-with-your-own-ideas.md
      - Unpacking Tech Systems: term1/unpacking-tech-systems.md
      - Atlas of Weak Signals: term1/02-Atlas of Weak Signals.md
      - Fundamentals for Future Makers: term1/fundamentals-for-future-makers.md
      - Narratives 1: term1/Narratives-1.md
      - Mind Maps: term1/mind-maps.md
      - Term 2: term2/index.md
      - Cognative Orgies: term2/cognitive-orgies.md
      - Extended Intelligence: term2/Extended-Intelligence-II.md
      - Narratives 2: term2/Narratives 2.md
      - Term 3: term3/index.md
  - Personal Work: Personal Work/index.md
  - Archive: archive/index.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: black
    accent: white
  font:
    # See available fonts at https://fonts.google.com/
    text: Roboto Condensed
    code: Cutive Mono

    extra_css:
    - stylesheets/extra.css
    - https://fonts.googleapis.com/css2?family=BBH+Sans+Bogle&display=swap

  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - mkdocs-video

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css

extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=BBH+Sans+Bogle&display=swap

docs_dir: docs
use_directory_urls: false
